### ISSUE TITLE
Not playing nicely with LastPass

### ISSUE THREAD

**Issue by adamsilverstein** [markjaquith/wp-feature-better-passwords#2]
Overall looks great, noticed an issue when trying to use LastPass to generate my password:  once I choose 'generate password' in lastpass, the field shows a 'mismatch'; assuming that is happening with the hidden field and can take a closer look.

Here is a screencast:

http://cl.ly/image/2O2v1h1c262U

**Comment by markjaquith** [comment]
It should be mirroring the password on form submit. Is LastPass hooking in BEFORE the JS can fire? If so, we will have to mirror on every change of the first pw field.

**Comment by adamsilverstein** [comment]
Looking into this more now...

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/markjaquith/wp-feature-better-passwords/pull/4

It looks like LastPass ignores the plaintext 'pass1' password field when pasting in its generated password (even though it gives me a generate password icon there). It updates pass2 only, thus we get a 'mismatch' error.

My solution, which resolves the issue in my initial local testing in Chrome, was to copy any changes to the pass2 field back to pass1. Here is a screencast of me using LastPass after this change: http://cl.ly/46042T3z2e1e
